# Generated by Django 5.0.2 on 2024-03-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chemistry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemistrytopic",
            name="content",
        ),
    ]
